version: '3'
services:
  esphome:
    container_name: esphome
    privileged: true
    network_mode: host
    image: ${ESPHOME_IMAGE}
    environment:
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/config:/config
      - ${PWD}/../esphome-boards:/config/esphome-boards
      - ${PWD}/../esphome-common:/config/esphome-common
      - ${PWD}/../esphome-devices:/config/esphome-devices
      - ${PWD}/../esphome-units:/config/esphome-units
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
