packages:
  board:  !include boards/d1.nodemcu_32s.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-d1-6400'
      friendly_name:   'Electropulse-D1-6400'
      project_version: '1.2.1'
      pulse_rate:      '6400'
      pulse_pin:       '25'
      pulse_led_pin:   '2'
      status_led_pin:  '2'
