packages:
  board:  !include
    file: boards/m1.esp32c3_supermini_dio.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-m1-6400'
      friendly_name:   'Electropulse-M1-6400'
      project_version: '1.2.2'
      pulse_rate:      '6400'
      pulse_pin:       '5'
