packages:
  board:  !include
    file: boards/n1.nodemcu_32s.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-n1-6400'
      friendly_name:   'Electropulse-N1-6400'
      project_version: '1.2.3'
      pulse_rate:      '6400'
      pulse_pin:       '25'
