packages:
  board:  !include
    file: boards/c1.luatos_core_esp32c3_dio.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-c1-6400'
      friendly_name:   'Electropulse-C1-6400'
      project_version: '1.2.3'
      pulse_rate:      '6400'
      pulse_pin:       '6'
