packages:
  board:  !include
    file: boards/n1.nodemcu_32s.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-n1'
      device_name:     'Electropulse-N1'
      device_number:   '01'
      project_version: '2.0.0'
      pulse_rate:      '6400'
      pulse_pin:       '25'
