packages:
  board:  !include
    file: boards/m1.esp32c3_supermini_dio.yaml
  common: !include
    file: common/common.yaml
    vars:
      <<: !include secrets.yaml
  device: !include
    file: devices/electropulse.yaml
    vars:
      project_name:    'electropulse-m1'
      device_name:     'Electropulse-M1'
      device_number:   '02'
      project_version: '2.1.0'
      pulse_rate:      '6400'
      pulse_pin:       '5'
