substitutions:
  <<: !include secrets.yaml
  device_number: '01'

packages:
  devices: github://ivanych/esphome-devices/relay_2m_sdr3.yaml@1.0.0
  #devices: !include esphome-devices/relay_2m_sdr3.yaml
