# https://esphome.io/devices/nodemcu_esp32.html
# https://docs.ai-thinker.com/en/esp32/boards/nodemcu_32s

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

output:
  - platform: gpio
    pin:
      number: 2
      inverted: false
    id: output_onboard_led

# В текущей версии esphome:2024.2.0 использовать пин 2 повторно нельзя
#status_led:
#  pin: 2
