defaults:
  timezone: "Europe/Moscow"
  device: "vodomers"
  friendly_device: "Vodomers"
  version: "0.1.0"

esphome:
  name: ${device}-${model}-${number}
  friendly_name: ${friendly_device}-${friendly_model}-${number}
  comment: "Модуль для чтения показаний счётчиков воды по интерфейсу RS485"
  project:
    name: ivanych.${device}-${model}
    version: ${version}

time:
  - platform: homeassistant
    id: time_homeassistant
    timezone: ${timezone}

uart:
  tx_pin: 21
  rx_pin: 20
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  debug:

external_components:
  - source:
      type: local
      path: components

sensor:
  - platform: pulsar_rs485
    pm_2_5:
      name: "Volume"
    update_interval: 10s
    cold:
      name: "Cold"
    hot:
      name: "Hot"
